name: baeldung 

services:
  api:
    image: baeldung/fastapi-template:1.0.0
    container_name: fastapi
    build:
      context: api
      dockerfile: Dockerfile
    command: uvicorn app:app --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
    depends_on:
      database:
        condition: service_healthy
    networks:
      - system

  database:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    user: ${POSTGRES_USER}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    networks:
      - system
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DATABASE}"]
      interval: 30s
      timeout: 3s
      retries: 5

networks:
  system:
    driver: bridge